import Header from '@/components/header/Header';
import Head from 'next/head';
import styled from 'styled-components';

const MainBack = styled.div`
  width: 100vw;
  height: 100vh;
  background-color: ${(props) => props.theme.bgColor};
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
`;
const FullWrap = styled.div`
  width: 70vw;
  height: 80vh;
  padding: 90px 50px;
  font-family: 'Montserrat';
  border-radius: 20px;
  display: grid;
  grid-template-columns: 0.3fr 0.7fr;
  background: ${(props) => props.theme.rightBg};
  & > div {
    overflow-x: hidden;
  }
`;

export default function Index() {
  //   const LocalTheme = window.localStorage.getItem('theme') || 'light';
  //   const [themeMode, setThemeMode] = useState(LocalTheme) || 'light';
  //   const theme = themeMode === 'light' ? lightMode : darkMode;
  //   const toggleTheme = useCallback(() => {
  //     if (themeMode === 'light') {
  //       setThemeMode('dark');
  //       window.localStorage.setItem('theme', 'dark');
  //     } else {
  //       setThemeMode('light');
  //       window.localStorage.setItem('theme', 'light');
  //     }
  //   }, [themeMode]);

  return (
    <>
      <Head>
        <title>HangBook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ThemeProvider theme={theme}> */}
      <MainBack>
        {/* <ThemeChange
            title={theme === lightMode ? '🌚' : '🌝'}
            clickToModeChange={toggleTheme}
          /> */}
        {/* <HashRouter> */}
        <FullWrap>
          <Header />❌
          <div>
            {/* <Switch>
                  <Route path="/" component={Today} exact />
                  <Route path="/bestSellers" component={BestSellerMain} />
                  <Route path="/searchBooks" component={SearchBookMain} />
                </Switch> */}
          </div>
        </FullWrap>
        {/* </HashRouter> */}
      </MainBack>
      {/* </ThemeProvider> */}
    </>
  );
}
